### ISSUE TITLE
[OCP-4.x][GCP] Default storageclass ps-ssd needs to be created

### ISSUE THREAD

**Issue by aakarshg** [openshift-scale/scale-ci-deploy#73]
https://github.com/openshift-scale/scale-ci-deploy/blob/master/docs/ocp4_gcp.md#openshift_prometheus_storage_class and https://github.com/openshift-scale/scale-ci-deploy/blob/master/docs/ocp4_gcp.md#openshift_prometheus_storage_class use pd-ssd as the defaults, which is not created by default. For this to work, sc can be created as follows:

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pd-ssd
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
```
